import React from 'react'

const Posts = () => {
  return (
    <>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      <div>Hello Posts</div>
      </>
  )
}

export default Posts
